"""bot/handlers/deliver.py — Deliver the complete Ad Pack with Canva affiliate links."""
import io
from telegram import Message, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ContextTypes

from bot.session import sessions
from bot.links import get_canva, whatsapp_link, instagram_caption, whatsapp_text, google_ad_block, poster_block
from config import State, BUSINESS_TYPES, ALL_PLATFORMS


async def deliver_full_pack(message: Message, context: ContextTypes.DEFAULT_TYPE,
                             user_id: int, img_url=None, img_bytes=None):
    session = sessions.get(user_id)
    copy = session.current_copy

    # 1. Send image
    try:
        caption = "🖼️ *Your AI-generated poster!*\n_Generated by Pollinations.ai — globally available_"
        if img_url:
            await context.bot.send_photo(chat_id=message.chat_id, photo=img_url,
                                          caption=caption, parse_mode="Markdown")
        elif img_bytes:
            await context.bot.send_photo(chat_id=message.chat_id, photo=io.BytesIO(img_bytes),
                                          caption=caption, parse_mode="Markdown")
        else:
            await message.reply_text("⚠️ Image generation failed — see Canva link below.")
    except Exception:
        await message.reply_text("⚠️ Couldn't send the image — see Canva link below.")

    # 2. Build copy pack
    ig  = instagram_caption(copy)
    wa  = whatsapp_text(copy)
    g   = google_ad_block(copy)
    p   = poster_block(copy)
    wa_url     = whatsapp_link(wa)
    canva_url  = get_canva(session.business_type, session.platform)

    text = (
        "🎁 *Your Complete Ad Pack:*\n\n"
        "━━━━━━━━━━━━━━\n"
        "📸 *Instagram Caption:*\n" + ig + "\n\n"
        "━━━━━━━━━━━━━━\n"
        "💬 *WhatsApp Message:*\n" + wa
    )
    if g:
        text += "\n\n━━━━━━━━━━━━━━\n" + g
    if p:
        text += "\n\n━━━━━━━━━━━━━━\n" + p

    text += (
        "\n\n━━━━━━━━━━━━━━\n"
        f"🔀 *A/B Headline:* _{copy.get('ab_variation','—')}_\n"
        f"🎯 *Audience:* _{copy.get('audience_description','—')}_"
    )

    await _send_long(message, text, parse_mode="Markdown")

    # 3. Action buttons (Canva link is affiliate-tagged = passive $$)
    await message.reply_text(
        "✅ *Done! Share or edit your ad:*",
        parse_mode="Markdown",
        reply_markup=InlineKeyboardMarkup([
            [InlineKeyboardButton("💬 Share on WhatsApp", url=wa_url)],
            [InlineKeyboardButton("🎨 Edit on Canva (free)", url=canva_url)],
            [InlineKeyboardButton("🔁 Make Another Ad", callback_data="action:new_ad")],
            [InlineKeyboardButton("📚 My History",      callback_data="action:history")],
            [InlineKeyboardButton("⭐ Upgrade to PRO",  callback_data="buy:monthly")] if not session.is_pro else
            [InlineKeyboardButton(f"⭐ PRO — {session.pro_days_remaining()}d left", callback_data="buy:info")],
        ])
    )

    session.save_to_history({
        "product": session.product_name,
        "headline": copy.get("headline",""),
        "body": copy.get("body",""),
        "cta": copy.get("cta",""),
        "hashtags": copy.get("hashtags",[]),
        "image_url": img_url or "",
        "platform": session.platform,
    })
    session.state = State.DONE


async def deliver_copy_only(message: Message, context: ContextTypes.DEFAULT_TYPE, user_id: int):
    session = sessions.get(user_id)
    copy = session.current_copy
    ig = instagram_caption(copy)
    wa = whatsapp_text(copy)
    canva_url = get_canva(session.business_type, session.platform)

    await _send_long(message,
        "📦 *Ad Copy Pack:*\n\n📸 *Instagram:*\n" + ig + "\n\n💬 *WhatsApp:*\n" + wa,
        parse_mode="Markdown"
    )
    await message.reply_text(
        "🎨 Use Canva below to create your poster from this copy:",
        reply_markup=InlineKeyboardMarkup([
            [InlineKeyboardButton("🎨 Open Canva Template", url=canva_url)],
            [InlineKeyboardButton("💬 Share on WhatsApp",   url=whatsapp_link(wa))],
            [InlineKeyboardButton("🔁 Make Another Ad",     callback_data="action:new_ad")],
        ])
    )
    session.state = State.DONE


async def handle_action(update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    user_id = query.from_user.id
    action  = query.data.split(":",1)[1]

    if action == "new_ad":
        session = sessions.get(user_id)
        session.reset_for_new_ad()
        session.state = State.CHOOSE_BUSINESS
        from config import BUSINESS_TYPES
        rows = [[InlineKeyboardButton(l, callback_data=f"btype:{v}")] for l,v in BUSINESS_TYPES.items()]
        await query.message.reply_text(
            "👇 *Choose your business type:*", parse_mode="Markdown",
            reply_markup=InlineKeyboardMarkup(rows)
        )
    elif action == "history":
        from bot.handlers.history import show_history
        await show_history(query.message, context, user_id)
    elif action == "info":
        pass   # handled by monetization module


async def _send_long(message: Message, text: str, **kw):
    for chunk in [text[i:i+4000] for i in range(0, len(text), 4000)]:
        await message.reply_text(chunk, **kw)
